name: CI - Develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Instalar .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ProyectoComunas.sln
      
    - name: Build
      run: dotnet build ProyectoComunas.sln --no-restore
      
    - name: Test
      run: dotnet test ProyectoComunas.sln --no-build --verbosity normal
